from building import *

cwd = GetCurrentDir()
src = [] 
CPPPATH = [cwd + '/../include']
group = []

if GetDepend(['RT_USING_PIN']):
    src = src + ['pin.c']
if GetDepend(['RT_USING_HWBUTTON']):
    src = src + ['hwbutton.c']	

if len(src):
    group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
